import type { Metadata } from 'next';

import { Cover } from '@/widgets/cover';
import {
  CatalogSection,
  TextSection,
  PopularProducts,
} from '@/widgets/page-sections';

import styles from './page.module.css';

// Отказать от использования моковых данных
import { mainPage, porducts } from '@/temp-data';
import { Modal } from '@/shared/modal/modal';

export const metadata: Metadata = {
  title: 'Pallada',
  description: 'Generated by create next app',
};

export default async function Home() {
  return (
    <main className={styles.main}>
      <Cover />
      <CatalogSection />
      <TextSection
        text={mainPage.text.content}
        headline={mainPage.text.headline}
      />
      {/*<PopularProducts headline="Популярные товары" products={porducts} />*/}

    </main>
  );
}
