import type { Metadata } from 'next';

import { Cover } from '@/widgets/cover';
import {
  CatalogSection,
  TextSection,
  PopularProducts,
} from '@/widgets/page-sections';

import styles from './page.module.css';

// Отказать от использования моковых данных
import { mainPage, porducts } from '@/temp-data';

export const metadata: Metadata = {
  title: 'Pallada',
  description: 'Generated by create next app',
};

async function getCategories() {
  const res = await fetch(
    'https://api.pallada-mo.ru/api/categories?pagination[page]=1&pagination[pageSize]=50&sort=name&populate=*'
  );

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data');
  }

  return res.json();
}

export default async function Home() {
  const { data: categories } = await getCategories();

  return (
    <main className={styles.main}>
      <Cover />
      <CatalogSection categories={categories} />
      <TextSection
        text={mainPage.text.content}
        headline={mainPage.text.headline}
      />
      <PopularProducts headline="Популярные товары" payload={porducts} />
    </main>
  );
}
