import type { Metadata } from 'next';

import { Cover } from '@/widgets/cover';
import {
  CatalogSection,
  TextSection,
} from '@/widgets/page-sections';

import styles from './page.module.css';

// Отказать от использования моковых данных
import { mainPage } from '@/temp-data';

export const metadata: Metadata = {
  title: 'Pallada',
  description: 'Generated by create next app',
};

export default async function Home() {
  return (
    <main className={styles.main}>
      <Cover />
      <CatalogSection />
      <TextSection
        text={mainPage.text.content}
        headline={mainPage.text.headline}
      />
    </main>
  );
}
